### ISSUE TITLE
issue about CoBiRGB

### ISSUE THREAD

**Issue by SandyJ01** [ceciliavision/zoom-learn-zoom#17]
when you introduce CoBiRGB, " where we use n×n RGB patches as features for CoBiRGB,and n should be larger for the 8X zoom (optimal n = 15) than the 4X zoom model (optimal n = 10)" ,
I can not understand the relation between zoom and n.
1.what's the relation between zoom and n?
2.why should set the patches as the feature,not only rgb?
3.If 1X zoom, how should I set the n?
Can you please tell me?

**Comment by ceciliavision** [comment]
The numbers are chosen by experimenting with varying sizes of patches. There is not a mathematical relation (if that's what you are asking). The intuition is that more challenging tasks would require more information to fill in the gap. I'm not sure what you meant by 'only rgb' since the patches are rgb patches?

I didn't have experiments with a 1X zoom, which I guess would be a model that learns the camera's ISP. I think it can be a rather easy task to learn, you can start out with the same setting e.g. n=10.
