### ISSUE TITLE
could you share iPhoneX-DSLR datasets?

### ISSUE THREAD

**Issue by yanmenglu** [ceciliavision/zoom-learn-zoom#18]
@ceciliavision thanks for your paper give me much help. Now I want to your iPhoneX-DSLR datasets to expriment. could you share the iPhoneX-DSLR datasets? Hope for your reply. thank you very much.

**Comment by yanmenglu** [comment]
if I want to get the pairs data iPhoneX-DSLR  . How  to do that?

**Comment by ceciliavision** [comment]
If you look at the supplementary material, which is linked from the [project page](https://people.eecs.berkeley.edu/~cecilia77/project-pages/zoom.html), Figure 3 shows a setup, and a few more details of how we captured roughly-aligned smartphone-DSLR pairs. I cannot promise to release the smartphone pairs soon due to time constraints.

**Comment by yanmenglu** [comment]
Thanks a lot. would you like to give me some iPhoneX-DSLR train data samples?

**Comment by qianzhang2018** [comment]
Is there a plan to release this data set in the future? @ceciliavision

**Comment by ceciliavision** [comment]
> Is there a plan to release this data set in the future? @ceciliavision

I might, but I didn't see much values as it's a rather small dataset. It won't be sufficient for training from scratch, but can only serve the purpose of fine-tuning the network. Plus it would not be hard to capture a larger one on one's own.
